const media = {
  LoadRequest: jest.fn(mediaInfo => ({ mediaInfo })),
}

window.chrome = {
  cast: {
    media: {
      ...media,
      HdrType: { SDR: 'sdr', HDR: 'hdr', DV: 'dv' },
      HlsSegmentFormat: {
        AAC: 'aac',
        AC3: 'ac3',
        MP3: 'mp3',
        TS: 'ts',
        TS_AAC: 'ts_aac',
        E_AC3: 'e_ac3',
        FMP4: 'fmp4',
      },
      HlsVideoSegmentFormat: { MPEG2_TS: 'mpeg2_ts', FMP4: 'fmp4' },
      MediaCommand: {
        PAUSE: 'pause',
        SEEK: 'seek',
        STREAM_VOLUME: 'stream_volume',
        STREAM_MUTE: 'stream_mute',
      },
      QueueType: {
        ALBUM: 'ALBUM',
        PLAYLIST: 'PLAYLIST',
        AUDIOBOOK: 'AUDIOBOOK',
        RADIO_STATION: 'RADIO_STATION',
        PODCAST_SERIES: 'PODCAST_SERIES',
        TV_SERIES: 'TV_SERIES',
        VIDEO_PLAYLIST: 'VIDEO_PLAYLIST',
        LIVE_TV: 'LIVE_TV',
        MOVIE: 'MOVIE',
      },
      ContainerType: { GENERIC_CONTAINER: 0, AUDIOBOOK_CONTAINER: 1 },
      MetadataType: {
        GENERIC: 0,
        MOVIE: 1,
        TV_SHOW: 2,
        MUSIC_TRACK: 3,
        PHOTO: 4,
        AUDIOBOOK_CHAPTER: 5,
      },
      PlayerState: {
        IDLE: 'IDLE',
        PLAYING: 'PLAYING',
        PAUSED: 'PAUSED',
        BUFFERING: 'BUFFERING',
      },
      RepeatMode: {
        OFF: 'REPEAT_OFF',
        ALL: 'REPEAT_ALL',
        SINGLE: 'REPEAT_SINGLE',
        ALL_AND_SHUFFLE: 'REPEAT_ALL_AND_SHUFFLE',
      },
      ResumeState: {
        PLAYBACK_START: 'PLAYBACK_START',
        PLAYBACK_PAUSE: 'PLAYBACK_PAUSE',
      },
      StreamType: { BUFFERED: 'BUFFERED', LIVE: 'LIVE', OTHER: 'OTHER' },
      IdleReason: {
        CANCELLED: 'CANCELLED',
        INTERRUPTED: 'INTERRUPTED',
        FINISHED: 'FINISHED',
        ERROR: 'ERROR',
      },
      TrackType: { TEXT: 'TEXT', AUDIO: 'AUDIO', VIDEO: 'VIDEO' },
      TextTrackType: {
        SUBTITLES: 'SUBTITLES',
        CAPTIONS: 'CAPTIONS',
        DESCRIPTIONS: 'DESCRIPTIONS',
        CHAPTERS: 'CHAPTERS',
        METADATA: 'METADATA',
      },
      TextTrackEdgeType: {
        NONE: 'NONE',
        OUTLINE: 'OUTLINE',
        DROP_SHADOW: 'DROP_SHADOW',
        RAISED: 'RAISED',
        DEPRESSED: 'DEPRESSED',
      },
      TextTrackWindowType: {
        NONE: 'NONE',
        NORMAL: 'NORMAL',
        ROUNDED_CORNERS: 'ROUNDED_CORNERS',
      },
      TextTrackFontGenericFamily: {
        SANS_SERIF: 'SANS_SERIF',
        MONOSPACED_SANS_SERIF: 'MONOSPACED_SANS_SERIF',
        SERIF: 'SERIF',
        MONOSPACED_SERIF: 'MONOSPACED_SERIF',
        CASUAL: 'CASUAL',
        CURSIVE: 'CURSIVE',
        SMALL_CAPITALS: 'SMALL_CAPITALS',
      },
      TextTrackFontStyle: {
        NORMAL: 'NORMAL',
        BOLD: 'BOLD',
        BOLD_ITALIC: 'BOLD_ITALIC',
        ITALIC: 'ITALIC',
      },
      UserAction: {
        LIKE: 'LIKE',
        DISLIKE: 'DISLIKE',
        FOLLOW: 'FOLLOW',
        UNFOLLOW: 'UNFOLLOW',
      },
      DEFAULT_MEDIA_RECEIVER_APP_ID: 'CC1AD845',
      timeout: {
        load: 0,
        P: 0,
        getStatus: 0,
        play: 0,
        pause: 0,
        seek: 0,
        stop: 0,
        T: 0,
        setVolume: 0,
        O: 0,
        editTracksInfo: 0,
        l: 0,
        queue: 0,
      },
    },
    VERSION: [1, 2],
    Ic: true,
    usingPresentationApi: true,
    AutoJoinPolicy: {
      CUSTOM_CONTROLLER_SCOPED: 'custom_controller_scoped',
      TAB_AND_ORIGIN_SCOPED: 'tab_and_origin_scoped',
      ORIGIN_SCOPED: 'origin_scoped',
      PAGE_SCOPED: 'page_scoped',
    },
    DefaultActionPolicy: {
      CREATE_SESSION: 'create_session',
      CAST_THIS_TAB: 'cast_this_tab',
    },
    Capability: {
      VIDEO_OUT: 'video_out',
      AUDIO_OUT: 'audio_out',
      VIDEO_IN: 'video_in',
      AUDIO_IN: 'audio_in',
      MULTIZONE_GROUP: 'multizone_group',
    },
    ErrorCode: {
      CANCEL: 'cancel',
      TIMEOUT: 'timeout',
      API_NOT_INITIALIZED: 'api_not_initialized',
      INVALID_PARAMETER: 'invalid_parameter',
      EXTENSION_NOT_COMPATIBLE: 'extension_not_compatible',
      EXTENSION_MISSING: 'extension_missing',
      RECEIVER_UNAVAILABLE: 'receiver_unavailable',
      SESSION_ERROR: 'session_error',
      CHANNEL_ERROR: 'channel_error',
      LOAD_MEDIA_FAILED: 'load_media_failed',
    },
    ReceiverAvailability: {
      AVAILABLE: 'available',
      UNAVAILABLE: 'unavailable',
    },
    SenderPlatform: { CHROME: 'chrome', IOS: 'ios', ANDROID: 'android' },
    ReceiverType: {
      CAST: 'cast',
      DIAL: 'dial',
      HANGOUT: 'hangout',
      CUSTOM: 'custom',
    },
    DialAppState: { RUNNING: 'running', STOPPED: 'stopped', ERROR: 'error' },
    ReceiverAction: { CAST: 'cast', STOP: 'stop' },
    SessionStatus: {
      CONNECTED: 'connected',
      DISCONNECTED: 'disconnected',
      STOPPED: 'stopped',
    },
    VolumeControlType: {
      ATTENUATION: 'attenuation',
      FIXED: 'fixed',
      MASTER: 'master',
    },
    timeout: {
      requestSession: 60000,
      leaveSession: 3000,
      stopSession: 3000,
      setReceiverVolume: 3000,
      sendCustomMessage: 3000,
    },
    Xa: 'auto-join',
    tb: 'cast-session_',
    isAvailable: true,
    Ta: true,
  },
}
